package com.hushunjian.gradle.mybatis.mapper;

import com.hushunjian.gradle.mybatis.domain.MeetingPersonRelation;
import com.hushunjian.gradle.mybatis.domain.MeetingPersonRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MeetingPersonRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    long countByExample(MeetingPersonRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int deleteByExample(MeetingPersonRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Delete({
        "delete from meeting_person_relation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Insert({
        "insert into meeting_person_relation (id, meet_id, ",
        "meet_person_depart, meet_person_id, ",
        "meet_person_name, meet_person_open_id, ",
        "meet_person_role, meet_phone_number)",
        "values (#{id,jdbcType=BIGINT}, #{meetId,jdbcType=BIGINT}, ",
        "#{meetPersonDepart,jdbcType=VARCHAR}, #{meetPersonId,jdbcType=VARCHAR}, ",
        "#{meetPersonName,jdbcType=VARCHAR}, #{meetPersonOpenId,jdbcType=VARCHAR}, ",
        "#{meetPersonRole,jdbcType=VARCHAR}, #{meetPhoneNumber,jdbcType=VARCHAR})"
    })
    int insert(MeetingPersonRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int insertSelective(MeetingPersonRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    List<MeetingPersonRelation> selectByExample(MeetingPersonRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Select({
        "select",
        "id, meet_id, meet_person_depart, meet_person_id, meet_person_name, meet_person_open_id, ",
        "meet_person_role, meet_phone_number",
        "from meeting_person_relation",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("com.hushunjian.gradle.mybatis.mapper.MeetingPersonRelationMapper.BaseResultMap")
    MeetingPersonRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") MeetingPersonRelation record, @Param("example") MeetingPersonRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExample(@Param("record") MeetingPersonRelation record, @Param("example") MeetingPersonRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByPrimaryKeySelective(MeetingPersonRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_person_relation
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Update({
        "update meeting_person_relation",
        "set meet_id = #{meetId,jdbcType=BIGINT},",
          "meet_person_depart = #{meetPersonDepart,jdbcType=VARCHAR},",
          "meet_person_id = #{meetPersonId,jdbcType=VARCHAR},",
          "meet_person_name = #{meetPersonName,jdbcType=VARCHAR},",
          "meet_person_open_id = #{meetPersonOpenId,jdbcType=VARCHAR},",
          "meet_person_role = #{meetPersonRole,jdbcType=VARCHAR},",
          "meet_phone_number = #{meetPhoneNumber,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MeetingPersonRelation record);
}