package com.hushunjian.gradle.mybatis.mapper;

import com.hushunjian.gradle.mybatis.domain.MeetingManage;
import com.hushunjian.gradle.mybatis.domain.MeetingManageExample;
import com.hushunjian.gradle.mybatis.domain.MeetingManageWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface MeetingManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    long countByExample(MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int deleteByExample(MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Delete({
        "delete from meeting_manage",
        "where meet_id = #{meetId,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long meetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Insert({
        "insert into meeting_manage (meet_id, meet_area, ",
        "meet_create_person_id, meet_create_person_name, ",
        "meet_create_person_open_id, meet_main, ",
        "meet_status, meet_time, ",
        "meet_adjunct_address, meet_agenda, ",
        "meet_general, meet_img, ",
        "meet_summary)",
        "values (#{meetId,jdbcType=BIGINT}, #{meetArea,jdbcType=VARCHAR}, ",
        "#{meetCreatePersonId,jdbcType=VARCHAR}, #{meetCreatePersonName,jdbcType=VARCHAR}, ",
        "#{meetCreatePersonOpenId,jdbcType=VARCHAR}, #{meetMain,jdbcType=VARCHAR}, ",
        "#{meetStatus,jdbcType=INTEGER}, #{meetTime,jdbcType=VARCHAR}, ",
        "#{meetAdjunctAddress,jdbcType=LONGVARCHAR}, #{meetAgenda,jdbcType=LONGVARCHAR}, ",
        "#{meetGeneral,jdbcType=LONGVARCHAR}, #{meetImg,jdbcType=LONGVARCHAR}, ",
        "#{meetSummary,jdbcType=LONGVARCHAR})"
    })
    int insert(MeetingManageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int insertSelective(MeetingManageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    List<MeetingManageWithBLOBs> selectByExampleWithBLOBs(MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    List<MeetingManage> selectByExample(MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Select({
        "select",
        "meet_id, meet_area, meet_create_person_id, meet_create_person_name, meet_create_person_open_id, ",
        "meet_main, meet_status, meet_time, meet_adjunct_address, meet_agenda, meet_general, ",
        "meet_img, meet_summary",
        "from meeting_manage",
        "where meet_id = #{meetId,jdbcType=BIGINT}"
    })
    @ResultMap("com.hushunjian.gradle.mybatis.mapper.MeetingManageMapper.ResultMapWithBLOBs")
    MeetingManageWithBLOBs selectByPrimaryKey(Long meetId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") MeetingManageWithBLOBs record, @Param("example") MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") MeetingManageWithBLOBs record, @Param("example") MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExample(@Param("record") MeetingManage record, @Param("example") MeetingManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByPrimaryKeySelective(MeetingManageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Update({
        "update meeting_manage",
        "set meet_area = #{meetArea,jdbcType=VARCHAR},",
          "meet_create_person_id = #{meetCreatePersonId,jdbcType=VARCHAR},",
          "meet_create_person_name = #{meetCreatePersonName,jdbcType=VARCHAR},",
          "meet_create_person_open_id = #{meetCreatePersonOpenId,jdbcType=VARCHAR},",
          "meet_main = #{meetMain,jdbcType=VARCHAR},",
          "meet_status = #{meetStatus,jdbcType=INTEGER},",
          "meet_time = #{meetTime,jdbcType=VARCHAR},",
          "meet_adjunct_address = #{meetAdjunctAddress,jdbcType=LONGVARCHAR},",
          "meet_agenda = #{meetAgenda,jdbcType=LONGVARCHAR},",
          "meet_general = #{meetGeneral,jdbcType=LONGVARCHAR},",
          "meet_img = #{meetImg,jdbcType=LONGVARCHAR},",
          "meet_summary = #{meetSummary,jdbcType=LONGVARCHAR}",
        "where meet_id = #{meetId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(MeetingManageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Update({
        "update meeting_manage",
        "set meet_area = #{meetArea,jdbcType=VARCHAR},",
          "meet_create_person_id = #{meetCreatePersonId,jdbcType=VARCHAR},",
          "meet_create_person_name = #{meetCreatePersonName,jdbcType=VARCHAR},",
          "meet_create_person_open_id = #{meetCreatePersonOpenId,jdbcType=VARCHAR},",
          "meet_main = #{meetMain,jdbcType=VARCHAR},",
          "meet_status = #{meetStatus,jdbcType=INTEGER},",
          "meet_time = #{meetTime,jdbcType=VARCHAR}",
        "where meet_id = #{meetId,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(MeetingManage record);
}