package com.hushunjian.gradle.mybatis.mapper;

import com.hushunjian.gradle.mybatis.domain.Order;
import com.hushunjian.gradle.mybatis.domain.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Delete({
        "delete from hsj_order",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Insert({
        "insert into hsj_order (id, name)",
        "values (#{id,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Select({
        "select",
        "id, name",
        "from hsj_order",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @ResultMap("com.hushunjian.gradle.mybatis.mapper.OrderMapper.BaseResultMap")
    Order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hsj_order
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    @Update({
        "update hsj_order",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Order record);
}