package com.hushunjian.gradle.mybatis.domain;

public class MeetingManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private Long meetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_area
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_create_person_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetCreatePersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_create_person_name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetCreatePersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_create_person_open_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetCreatePersonOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_main
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetMain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_status
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private Integer meetStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_manage.meet_time
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_id
     *
     * @return the value of meeting_manage.meet_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public Long getMeetId() {
        return meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_id
     *
     * @param meetId the value for meeting_manage.meet_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetId(Long meetId) {
        this.meetId = meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_area
     *
     * @return the value of meeting_manage.meet_area
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetArea() {
        return meetArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_area
     *
     * @param meetArea the value for meeting_manage.meet_area
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetArea(String meetArea) {
        this.meetArea = meetArea == null ? null : meetArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_create_person_id
     *
     * @return the value of meeting_manage.meet_create_person_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetCreatePersonId() {
        return meetCreatePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_create_person_id
     *
     * @param meetCreatePersonId the value for meeting_manage.meet_create_person_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetCreatePersonId(String meetCreatePersonId) {
        this.meetCreatePersonId = meetCreatePersonId == null ? null : meetCreatePersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_create_person_name
     *
     * @return the value of meeting_manage.meet_create_person_name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetCreatePersonName() {
        return meetCreatePersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_create_person_name
     *
     * @param meetCreatePersonName the value for meeting_manage.meet_create_person_name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetCreatePersonName(String meetCreatePersonName) {
        this.meetCreatePersonName = meetCreatePersonName == null ? null : meetCreatePersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_create_person_open_id
     *
     * @return the value of meeting_manage.meet_create_person_open_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetCreatePersonOpenId() {
        return meetCreatePersonOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_create_person_open_id
     *
     * @param meetCreatePersonOpenId the value for meeting_manage.meet_create_person_open_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetCreatePersonOpenId(String meetCreatePersonOpenId) {
        this.meetCreatePersonOpenId = meetCreatePersonOpenId == null ? null : meetCreatePersonOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_main
     *
     * @return the value of meeting_manage.meet_main
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetMain() {
        return meetMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_main
     *
     * @param meetMain the value for meeting_manage.meet_main
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetMain(String meetMain) {
        this.meetMain = meetMain == null ? null : meetMain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_status
     *
     * @return the value of meeting_manage.meet_status
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public Integer getMeetStatus() {
        return meetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_status
     *
     * @param meetStatus the value for meeting_manage.meet_status
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetStatus(Integer meetStatus) {
        this.meetStatus = meetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_manage.meet_time
     *
     * @return the value of meeting_manage.meet_time
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetTime() {
        return meetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_manage.meet_time
     *
     * @param meetTime the value for meeting_manage.meet_time
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetTime(String meetTime) {
        this.meetTime = meetTime == null ? null : meetTime.trim();
    }
}