package com.hushunjian.gradle.mybatis.domain;

import java.util.ArrayList;
import java.util.List;

public class MeetingManageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public MeetingManageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMeetIdIsNull() {
            addCriterion("meet_id is null");
            return (Criteria) this;
        }

        public Criteria andMeetIdIsNotNull() {
            addCriterion("meet_id is not null");
            return (Criteria) this;
        }

        public Criteria andMeetIdEqualTo(Long value) {
            addCriterion("meet_id =", value, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdNotEqualTo(Long value) {
            addCriterion("meet_id <>", value, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdGreaterThan(Long value) {
            addCriterion("meet_id >", value, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdGreaterThanOrEqualTo(Long value) {
            addCriterion("meet_id >=", value, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdLessThan(Long value) {
            addCriterion("meet_id <", value, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdLessThanOrEqualTo(Long value) {
            addCriterion("meet_id <=", value, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdIn(List<Long> values) {
            addCriterion("meet_id in", values, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdNotIn(List<Long> values) {
            addCriterion("meet_id not in", values, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdBetween(Long value1, Long value2) {
            addCriterion("meet_id between", value1, value2, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetIdNotBetween(Long value1, Long value2) {
            addCriterion("meet_id not between", value1, value2, "meetId");
            return (Criteria) this;
        }

        public Criteria andMeetAreaIsNull() {
            addCriterion("meet_area is null");
            return (Criteria) this;
        }

        public Criteria andMeetAreaIsNotNull() {
            addCriterion("meet_area is not null");
            return (Criteria) this;
        }

        public Criteria andMeetAreaEqualTo(String value) {
            addCriterion("meet_area =", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaNotEqualTo(String value) {
            addCriterion("meet_area <>", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaGreaterThan(String value) {
            addCriterion("meet_area >", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaGreaterThanOrEqualTo(String value) {
            addCriterion("meet_area >=", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaLessThan(String value) {
            addCriterion("meet_area <", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaLessThanOrEqualTo(String value) {
            addCriterion("meet_area <=", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaLike(String value) {
            addCriterion("meet_area like", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaNotLike(String value) {
            addCriterion("meet_area not like", value, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaIn(List<String> values) {
            addCriterion("meet_area in", values, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaNotIn(List<String> values) {
            addCriterion("meet_area not in", values, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaBetween(String value1, String value2) {
            addCriterion("meet_area between", value1, value2, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetAreaNotBetween(String value1, String value2) {
            addCriterion("meet_area not between", value1, value2, "meetArea");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdIsNull() {
            addCriterion("meet_create_person_id is null");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdIsNotNull() {
            addCriterion("meet_create_person_id is not null");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdEqualTo(String value) {
            addCriterion("meet_create_person_id =", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdNotEqualTo(String value) {
            addCriterion("meet_create_person_id <>", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdGreaterThan(String value) {
            addCriterion("meet_create_person_id >", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdGreaterThanOrEqualTo(String value) {
            addCriterion("meet_create_person_id >=", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdLessThan(String value) {
            addCriterion("meet_create_person_id <", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdLessThanOrEqualTo(String value) {
            addCriterion("meet_create_person_id <=", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdLike(String value) {
            addCriterion("meet_create_person_id like", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdNotLike(String value) {
            addCriterion("meet_create_person_id not like", value, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdIn(List<String> values) {
            addCriterion("meet_create_person_id in", values, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdNotIn(List<String> values) {
            addCriterion("meet_create_person_id not in", values, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdBetween(String value1, String value2) {
            addCriterion("meet_create_person_id between", value1, value2, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonIdNotBetween(String value1, String value2) {
            addCriterion("meet_create_person_id not between", value1, value2, "meetCreatePersonId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameIsNull() {
            addCriterion("meet_create_person_name is null");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameIsNotNull() {
            addCriterion("meet_create_person_name is not null");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameEqualTo(String value) {
            addCriterion("meet_create_person_name =", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameNotEqualTo(String value) {
            addCriterion("meet_create_person_name <>", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameGreaterThan(String value) {
            addCriterion("meet_create_person_name >", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameGreaterThanOrEqualTo(String value) {
            addCriterion("meet_create_person_name >=", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameLessThan(String value) {
            addCriterion("meet_create_person_name <", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameLessThanOrEqualTo(String value) {
            addCriterion("meet_create_person_name <=", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameLike(String value) {
            addCriterion("meet_create_person_name like", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameNotLike(String value) {
            addCriterion("meet_create_person_name not like", value, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameIn(List<String> values) {
            addCriterion("meet_create_person_name in", values, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameNotIn(List<String> values) {
            addCriterion("meet_create_person_name not in", values, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameBetween(String value1, String value2) {
            addCriterion("meet_create_person_name between", value1, value2, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonNameNotBetween(String value1, String value2) {
            addCriterion("meet_create_person_name not between", value1, value2, "meetCreatePersonName");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdIsNull() {
            addCriterion("meet_create_person_open_id is null");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdIsNotNull() {
            addCriterion("meet_create_person_open_id is not null");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdEqualTo(String value) {
            addCriterion("meet_create_person_open_id =", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdNotEqualTo(String value) {
            addCriterion("meet_create_person_open_id <>", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdGreaterThan(String value) {
            addCriterion("meet_create_person_open_id >", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("meet_create_person_open_id >=", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdLessThan(String value) {
            addCriterion("meet_create_person_open_id <", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdLessThanOrEqualTo(String value) {
            addCriterion("meet_create_person_open_id <=", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdLike(String value) {
            addCriterion("meet_create_person_open_id like", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdNotLike(String value) {
            addCriterion("meet_create_person_open_id not like", value, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdIn(List<String> values) {
            addCriterion("meet_create_person_open_id in", values, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdNotIn(List<String> values) {
            addCriterion("meet_create_person_open_id not in", values, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdBetween(String value1, String value2) {
            addCriterion("meet_create_person_open_id between", value1, value2, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetCreatePersonOpenIdNotBetween(String value1, String value2) {
            addCriterion("meet_create_person_open_id not between", value1, value2, "meetCreatePersonOpenId");
            return (Criteria) this;
        }

        public Criteria andMeetMainIsNull() {
            addCriterion("meet_main is null");
            return (Criteria) this;
        }

        public Criteria andMeetMainIsNotNull() {
            addCriterion("meet_main is not null");
            return (Criteria) this;
        }

        public Criteria andMeetMainEqualTo(String value) {
            addCriterion("meet_main =", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainNotEqualTo(String value) {
            addCriterion("meet_main <>", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainGreaterThan(String value) {
            addCriterion("meet_main >", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainGreaterThanOrEqualTo(String value) {
            addCriterion("meet_main >=", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainLessThan(String value) {
            addCriterion("meet_main <", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainLessThanOrEqualTo(String value) {
            addCriterion("meet_main <=", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainLike(String value) {
            addCriterion("meet_main like", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainNotLike(String value) {
            addCriterion("meet_main not like", value, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainIn(List<String> values) {
            addCriterion("meet_main in", values, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainNotIn(List<String> values) {
            addCriterion("meet_main not in", values, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainBetween(String value1, String value2) {
            addCriterion("meet_main between", value1, value2, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetMainNotBetween(String value1, String value2) {
            addCriterion("meet_main not between", value1, value2, "meetMain");
            return (Criteria) this;
        }

        public Criteria andMeetStatusIsNull() {
            addCriterion("meet_status is null");
            return (Criteria) this;
        }

        public Criteria andMeetStatusIsNotNull() {
            addCriterion("meet_status is not null");
            return (Criteria) this;
        }

        public Criteria andMeetStatusEqualTo(Integer value) {
            addCriterion("meet_status =", value, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusNotEqualTo(Integer value) {
            addCriterion("meet_status <>", value, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusGreaterThan(Integer value) {
            addCriterion("meet_status >", value, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("meet_status >=", value, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusLessThan(Integer value) {
            addCriterion("meet_status <", value, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusLessThanOrEqualTo(Integer value) {
            addCriterion("meet_status <=", value, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusIn(List<Integer> values) {
            addCriterion("meet_status in", values, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusNotIn(List<Integer> values) {
            addCriterion("meet_status not in", values, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusBetween(Integer value1, Integer value2) {
            addCriterion("meet_status between", value1, value2, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("meet_status not between", value1, value2, "meetStatus");
            return (Criteria) this;
        }

        public Criteria andMeetTimeIsNull() {
            addCriterion("meet_time is null");
            return (Criteria) this;
        }

        public Criteria andMeetTimeIsNotNull() {
            addCriterion("meet_time is not null");
            return (Criteria) this;
        }

        public Criteria andMeetTimeEqualTo(String value) {
            addCriterion("meet_time =", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeNotEqualTo(String value) {
            addCriterion("meet_time <>", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeGreaterThan(String value) {
            addCriterion("meet_time >", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeGreaterThanOrEqualTo(String value) {
            addCriterion("meet_time >=", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeLessThan(String value) {
            addCriterion("meet_time <", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeLessThanOrEqualTo(String value) {
            addCriterion("meet_time <=", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeLike(String value) {
            addCriterion("meet_time like", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeNotLike(String value) {
            addCriterion("meet_time not like", value, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeIn(List<String> values) {
            addCriterion("meet_time in", values, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeNotIn(List<String> values) {
            addCriterion("meet_time not in", values, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeBetween(String value1, String value2) {
            addCriterion("meet_time between", value1, value2, "meetTime");
            return (Criteria) this;
        }

        public Criteria andMeetTimeNotBetween(String value1, String value2) {
            addCriterion("meet_time not between", value1, value2, "meetTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting_manage
     *
     * @mbg.generated do_not_delete_during_merge Sun May 19 10:56:54 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table meeting_manage
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}