package com.hushunjian.gradle.mybatis.domain;

public class MeetingPersonRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private Long meetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_person_depart
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetPersonDepart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_person_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetPersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_person_name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetPersonName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_person_open_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetPersonOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_person_role
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetPersonRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_person_relation.meet_phone_number
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String meetPhoneNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.id
     *
     * @return the value of meeting_person_relation.id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.id
     *
     * @param id the value for meeting_person_relation.id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_id
     *
     * @return the value of meeting_person_relation.meet_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public Long getMeetId() {
        return meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_id
     *
     * @param meetId the value for meeting_person_relation.meet_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetId(Long meetId) {
        this.meetId = meetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_person_depart
     *
     * @return the value of meeting_person_relation.meet_person_depart
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetPersonDepart() {
        return meetPersonDepart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_person_depart
     *
     * @param meetPersonDepart the value for meeting_person_relation.meet_person_depart
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetPersonDepart(String meetPersonDepart) {
        this.meetPersonDepart = meetPersonDepart == null ? null : meetPersonDepart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_person_id
     *
     * @return the value of meeting_person_relation.meet_person_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetPersonId() {
        return meetPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_person_id
     *
     * @param meetPersonId the value for meeting_person_relation.meet_person_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetPersonId(String meetPersonId) {
        this.meetPersonId = meetPersonId == null ? null : meetPersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_person_name
     *
     * @return the value of meeting_person_relation.meet_person_name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetPersonName() {
        return meetPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_person_name
     *
     * @param meetPersonName the value for meeting_person_relation.meet_person_name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetPersonName(String meetPersonName) {
        this.meetPersonName = meetPersonName == null ? null : meetPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_person_open_id
     *
     * @return the value of meeting_person_relation.meet_person_open_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetPersonOpenId() {
        return meetPersonOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_person_open_id
     *
     * @param meetPersonOpenId the value for meeting_person_relation.meet_person_open_id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetPersonOpenId(String meetPersonOpenId) {
        this.meetPersonOpenId = meetPersonOpenId == null ? null : meetPersonOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_person_role
     *
     * @return the value of meeting_person_relation.meet_person_role
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetPersonRole() {
        return meetPersonRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_person_role
     *
     * @param meetPersonRole the value for meeting_person_relation.meet_person_role
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetPersonRole(String meetPersonRole) {
        this.meetPersonRole = meetPersonRole == null ? null : meetPersonRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_person_relation.meet_phone_number
     *
     * @return the value of meeting_person_relation.meet_phone_number
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getMeetPhoneNumber() {
        return meetPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_person_relation.meet_phone_number
     *
     * @param meetPhoneNumber the value for meeting_person_relation.meet_phone_number
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setMeetPhoneNumber(String meetPhoneNumber) {
        this.meetPhoneNumber = meetPhoneNumber == null ? null : meetPhoneNumber.trim();
    }
}