package com.hushunjian.gradle.mybatis.domain;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_order.id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hsj_order.name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_order.id
     *
     * @return the value of hsj_order.id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_order.id
     *
     * @param id the value for hsj_order.id
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hsj_order.name
     *
     * @return the value of hsj_order.name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hsj_order.name
     *
     * @param name the value for hsj_order.name
     *
     * @mbg.generated Sun May 19 10:56:54 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}